"use client";
import Link from "next/link"; import {useSearchParams} from "next/navigation"; import {useEffect,useState} from "react"; import {onAuthStateChanged,type User} from "firebase/auth"; import {auth} from "../../../firebase";
type Poll={pollId:string;question:string;options:string[];active:boolean;showResults:boolean;counts?:Record<string,number>;totalVotes?:number;closesAt:string};
export default function Council(){const searchParams=useSearchParams();const teacherPreview=searchParams.get("teacherPreview")==="1";const [user,setUser]=useState<User|null>(null),[poll,setPoll]=useState<Poll|null>(null),[mine,setMine]=useState<number|null>(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);if(!u)setLoading(false)}),[]);
async function load(u:User){setLoading(true);try{const token=await u.getIdToken();const r=await fetch(`/api/academy-club/council${teacherPreview?"?teacherPreview=1":""}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message);setPoll(d.poll);setMine(Number.isInteger(d.myVote)?d.myVote:null)}catch(e){setMsg(e instanceof Error?e.message:"تعذر التحميل")}finally{setLoading(false)}}
useEffect(()=>{if(user)void load(user)},[user,teacherPreview]);
async function vote(i:number){if(!user||teacherPreview)return;setMsg("جارٍ حفظ صوتك...");const token=await user.getIdToken();const r=await fetch("/api/academy-club/council",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({optionIndex:i})});const d=await r.json();setMsg(r.ok?"تم تسجيل اختيارك ✅ ويمكنك تغييره ما دام التصويت مفتوحًا.":d.message);if(r.ok)await load(user)}
return <main dir="rtl" style={{minHeight:"100vh",background:"linear-gradient(180deg,#145b40 0,#18734f 230px,#f5faf7 230px)",fontFamily:"Arial",color:"#17352a",paddingBottom:50}}><header style={{maxWidth:900,margin:"0 auto",padding:"28px 16px 60px",color:"white",display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><div style={{color:"#f5d76e",fontWeight:900}}>🏅 نادي الأكاديمية</div><h1 style={{fontSize:"clamp(29px,7vw,44px)",margin:"7px 0"}}>🗳️ مجلس النادي</h1><p style={{margin:0,fontWeight:800}}>صوتك يشارك في صناعة بعض قرارات ناديك</p></div><Link href={teacherPreview?"/academy-club?teacherPreview=1":"/academy-club"} style={{color:"white",textDecoration:"none",border:"1px solid #ffffff66",borderRadius:14,padding:"10px 14px"}}>العودة للنادي ←</Link></header><section style={{maxWidth:720,margin:"-25px auto 0",padding:"0 16px"}}><div style={{background:"white",border:"2px solid #d8e8df",borderRadius:28,padding:"clamp(20px,5vw,34px)",boxShadow:"0 18px 45px #17352a20"}}>{loading?<h2>⏳ جارٍ فتح المجلس...</h2>:!user?<><h2>🔐 سجل دخولك أولًا</h2><Link href="/login">تسجيل الدخول</Link></>:!poll?<><div style={{fontSize:55}}>🪑</div><h2>لا يوجد تصويت مفتوح الآن</h2><p>عند طرح موضوع جديد سيظهر هنا لأعضاء النادي.</p></>:<><span style={{background:poll.active?"#e8f7ef":"#f1f5f9",padding:"7px 12px",borderRadius:999,fontWeight:900}}>{poll.active?"🟢 التصويت مفتوح":"🔒 التصويت مغلق"}</span>{teacherPreview&&<span style={{marginRight:8,background:"#fff8dc",padding:"7px 12px",borderRadius:999,fontWeight:900}}>👁️ معاينة المعلم</span>}<h2 style={{fontSize:"clamp(23px,5vw,31px)",lineHeight:1.6,color:"#176c46"}}>{poll.question}</h2><div style={{display:"grid",gap:12}}>{poll.options.map((o,i)=>{const count=poll.counts?.[String(i)]??0,total=poll.totalVotes??0,pct=total?Math.round(count/total*100):0;return <button key={i} disabled={!poll.active||teacherPreview} onClick={()=>void vote(i)} style={{textAlign:"right",padding:17,borderRadius:18,border:mine===i?"3px solid #c7961f":"2px solid #cfe2d8",background:mine===i?"#fff8dc":"#f8fcfa",font:"inherit",fontWeight:900,cursor:poll.active?"pointer":"default"}}><div>{mine===i?"✓ ":""}{o}</div>{poll.showResults&&<div style={{marginTop:9,fontSize:14,color:"#64748b"}}>{pct}% • {count} صوت</div>}</button>})}</div>{poll.showResults&&<p style={{fontWeight:900,color:"#7c5808"}}>إجمالي المشاركين: {poll.totalVotes??0}</p>}{teacherPreview&&<p style={{color:"#8a6500",fontWeight:800}}>المعاينة للعرض فقط؛ التصويت متاح لأعضاء النادي.</p>}{!poll.showResults&&<p style={{color:"#64748b",fontWeight:800}}>🔐 النتائج مخفية حتى يقرر المعلم إظهارها.</p>}</>}{msg&&<div style={{marginTop:16,padding:13,borderRadius:14,background:"#eef8f2",fontWeight:800}}>{msg}</div>}</div></section></main>}
