const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const id='12345678-1234-1234-1234-123456789abc';
function fixture(){
 class Timestamp{constructor(ms){this.ms=ms;}toMillis(){return this.ms;}}
 const documents=new Map(),writes=[],reads=[],tags=[];let authCalls=0;
 const active={studentName:'بطل',active:true,academyClubMembership:{active:true,expiresAt:'2099-01-01'}};
 documents.set('students/s1',active);documents.set('students/s2',{...active,studentName:'زميل'});
 const snapshot=(path)=>({id:path.split('/').at(-1),exists:documents.has(path),data:()=>documents.get(path)});
 function ref(path){return {path,doc:name=>ref(path+'/'+name),collection:name=>ref(path+'/'+name),get:async()=>{reads.push(path);return snapshot(path);},where:()=>query(path),orderBy:()=>query(path)};}
 function query(path){let maximum=Infinity,after='';const q={query:true,path,where:()=>q,orderBy:()=>q,limit:n=>{maximum=n;return q;},startAfter:v=>{after=v;return q;},get:async()=>{reads.push(path+':query');const rows=[...documents.keys()].filter(k=>k.startsWith(path+'/')&&k.split('/').length===path.split('/').length+1).sort().filter(k=>k.split('/').at(-1)>after).slice(0,maximum).map(snapshot);return {docs:rows,size:rows.length};}};return q;}
 const db={collection:ref,runTransaction:async fn=>fn({get:r=>r.get(),set:(r,d)=>{writes.push(r.path);documents.set(r.path,d);},update:(r,d)=>{writes.push(r.path);documents.set(r.path,{...documents.get(r.path),...d});}})};
 const auth={verifyIdToken:async token=>{authCalls++;if(token==='bad')throw Error();return token==='teacher'?{role:'teacher',uid:'t'}:{role:'student',uid:token,studentDocId:token};}};
 const cache=new Map();const mocks={'server-only':{},'node:crypto':require('node:crypto'),'next/cache':{unstable_cache:(fn,key)=>async()=>{const k=key.join();if(!cache.has(k))cache.set(k,await fn());return cache.get(k);},revalidateTag:tag=>{tags.push(tag);cache.clear();}},'next/server':{NextResponse:{json:(body,options)=>({body,status:options.status,headers:options.headers})}},'firebase-admin/firestore':{Timestamp,FieldPath:{documentId:()=> '__name__'},FieldValue:{serverTimestamp:()=>new Timestamp(Date.now())}},'../../firebase-admin':{getFirebaseAdmin:()=>({adminDb:db,adminAuth:auth})}};
 const load=(path)=>{const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>mocks[n],Date,Intl,URL,console,Error});return module.exports;};
 const helper=load('app/lib/clubNotices.ts');mocks['../../../lib/clubNotices']=helper;mocks['../../../../lib/clubNotices']=helper;
 const student=load('app/api/academy-club/notice/route.ts'),teacher=load('app/api/teacher/academy-club/notice/route.ts');
 const req=(who='s1',body={},suffix='')=>({url:'https://example.com/api'+suffix,headers:{get:()=>who?'Bearer '+who:null},json:async()=>body});
 const publish=()=>teacher.POST(req('teacher',{noticeId:id,title:'هام',text:'رسالة',allowReplies:true}));
 return {student,teacher,helper,req,publish,documents,writes,reads,tags,Timestamp,active,authCalls:()=>authCalls};
}
test('authentication and active membership protect notice and replies',async()=>{const f=fixture();for(const who of [null,'bad','missing'])assert.notEqual((await f.student.GET(f.req(who))).status,200);assert.equal((await f.teacher.POST(f.req('s1'))).status,403);assert.equal(f.writes.length,0);f.documents.set('students/s1',{...f.active,academyClubMembership:{active:true,expiresAt:'2020-01-01'}});assert.equal((await f.student.GET(f.req())).status,403);});
test('date-only expiry is valid through the Riyadh day; timestamps and disabled students are checked',()=>{const f=fixture();assert.equal(f.helper.isActiveClubStudent({...f.active,academyClubMembership:{active:true,expiresAt:'2026-10-07'}},new Date('2026-10-07T20:59:59Z')),true);assert.equal(f.helper.isActiveClubStudent({...f.active,academyClubMembership:{active:true,expiresAt:'2026-10-07'}},new Date('2026-10-07T21:00:00Z')),false);assert.equal(f.helper.isActiveClubStudent({...f.active,deleted:true}),false);assert.equal(f.helper.isActiveClubStudent({...f.active,academyClubMembership:{active:true,expiresAt:new f.Timestamp(1)}}),false);});
test('publish sends stable notifications only to valid members and repeat request is idempotent',async()=>{const f=fixture();f.documents.set('students/s2',{...f.active,academyClubMembership:{active:true,expiresAt:'2020-01-01'}});assert.equal((await f.publish()).body.notifiedMembers,1);const count=f.writes.length;assert.equal((await f.publish()).status,200);assert.equal(f.writes.length,count);const alert=f.documents.get('studentNotifications/club-notice-'+id+'-s1');assert.equal(alert.href,'/academy-club#club-important-notice');assert.ok(f.tags.some(t=>t.startsWith('student-notifications:')));});
test('students see only their own reply and cannot impersonate another member',async()=>{const f=fixture();await f.publish();f.documents.set('academyClubNotices/'+id+'/replies/s2',{text:'رد خاص آخر'});const r=await f.student.POST(f.req('s1',{noticeId:id,text:'ردي',studentId:'s2'}));assert.equal(r.status,200);assert.equal(f.documents.get('academyClubNotices/'+id+'/replies/s1').studentId,'s1');const result=await f.student.GET(f.req());assert.equal(result.body.reply.text,'ردي');assert.equal(JSON.stringify(result.body).includes('رد خاص آخر'),false);assert.equal(result.headers['Cache-Control'],'private, no-store');});
test('closed, replaced and teacher-preview notices reject replies without writes',async()=>{const f=fixture();await f.publish();const count=f.writes.length;assert.equal((await f.student.POST(f.req('teacher',{noticeId:id,text:'رد'},'?teacherPreview=1'))).status,403);assert.equal((await f.student.POST(f.req('s1',{noticeId:id.replace('a','b'),text:'رد'}))).status,400);assert.equal(f.writes.length,count);await f.teacher.PATCH(f.req('teacher',{noticeId:id,action:'closeReplies'}));assert.equal((await f.student.POST(f.req('s1',{noticeId:id,text:'رد'}))).status,400);await f.teacher.PATCH(f.req('teacher',{noticeId:id,action:'unpin'}));assert.equal((await f.student.GET(f.req())).body.notice,null);});
test('reply retries do not write twice and fast changes are throttled',async()=>{const f=fixture();await f.publish();const body={noticeId:id,text:'رد'};await f.student.POST(f.req('s1',body));const count=f.writes.length;assert.equal((await f.student.POST(f.req('s1',body))).status,200);assert.equal(f.writes.length,count);assert.equal((await f.student.POST(f.req('s1',{...body,text:'رد جديد'}))).status,429);});
test('large publication and oversized text fail before writes',async()=>{const f=fixture();assert.equal((await f.teacher.POST(f.req('teacher',{noticeId:id,title:'هام',text:'x'.repeat(3001)}))).status,400);for(let i=0;i<201;i++)f.documents.set('students/extra'+i,f.active);assert.equal((await f.publish()).status,409);assert.equal(f.writes.length,0);});
test('cache hits still authenticate membership and teacher reply pages are bounded',async()=>{const f=fixture();await f.publish();await f.student.GET(f.req());await f.student.GET(f.req());assert.equal(f.reads.filter(p=>p==='academyClubNotices/current').length,1);f.documents.set('students/s1',{...f.active,active:false});assert.equal((await f.student.GET(f.req())).status,403);for(let i=0;i<55;i++)f.documents.set('academyClubNotices/'+id+'/replies/member'+String(i).padStart(2,'0'),{studentName:'طالب',text:'رد'});const page=await f.teacher.GET(f.req('teacher'));assert.equal(page.body.replies.length,50);assert.ok(page.body.nextCursor);const next=await f.teacher.GET(f.req('teacher',{},'?cursor='+page.body.nextCursor));assert.equal(next.body.replies.length,5);});
