const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function fixture(){let calls=0,fail=false,decodeFail=false,width=4000,height=3000,blobSize=200000,requestedType,canvasSize,now=100;const bodies=[],cleanup=[];
 const module={exports:{}};const fakeDate=class extends Date{static now(){return now;}};
 class FakeImage{get naturalWidth(){return width;}get naturalHeight(){return height;}set src(v){if(v)queueMicrotask(()=>decodeFail?this.onerror?.():this.onload?.());}}
 const canvas={width:0,height:0,getContext:()=>({drawImage:()=>{canvasSize=[canvas.width,canvas.height];}}),toBlob:(cb,type)=>{requestedType=type;cb(new Blob([new Uint8Array(blobSize)],{type}));}};
 const code=ts.transpileModule(fs.readFileSync('app/lib/uploadCloudinary.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 vm.runInNewContext(code,{module,exports:module.exports,require,Blob,File,FormData,Response,URL:{createObjectURL:()=> 'blob:test',revokeObjectURL:u=>cleanup.push(u)},Image:FakeImage,document:{createElement:()=>canvas},setTimeout,clearTimeout,queueMicrotask,Date:fakeDate,fetch:async(u,opts)=>{calls++;bodies.push(opts.body);return Response.json(fail?{error:'failed'}:{secure_url:'https://res.cloudinary.com/ffv5igmg/image/upload/v1/test.jpg',public_id:'test'},{status:fail?500:200});}});
 const file=(type='image/jpeg',size=2000000)=>new File([new Uint8Array(size)],'sample.jpg',{type,lastModified:5});const upload=(f,preset='homework')=>{const body=new FormData();body.append('file',f);body.append('upload_preset',preset);return module.exports.uploadCloudinary('https://api.cloudinary.com/v1_1/ffv5igmg/image/upload',{method:'POST',body});};
 return {api:module.exports,file,upload,bodies,cleanup,getCalls:()=>calls,setFail:v=>fail=v,setDecodeFail:v=>decodeFail=v,setSize:(w,h)=>{width=w;height=h;},setOutputSize:v=>blobSize=v,getCanvasSize:()=>canvasSize,getType:()=>requestedType,expire:()=>now+=31*60000};}
test('large JPEG scales proportionally, uses high quality compression and cleans resources',async()=>{const f=fixture(),source=f.file(),out=await f.api.prepareImage(source);assert.ok(out.size<source.size);assert.deepEqual(f.getCanvasSize(),[2000,1500]);assert.equal(out.type,'image/jpeg');assert.equal(out.lastModified,5);assert.equal(f.cleanup.length,1);assert.equal(await f.api.prepareImage(source),out);});
test('small images are kept byte-for-byte and never upscaled',async()=>{const f=fixture();f.setSize(500,400);const source=f.file('image/jpeg',100000);assert.equal(await f.api.prepareImage(source),source);assert.equal(f.getCanvasSize(),undefined);assert.deepEqual({...f.api.imageDimensions(500,400)},{width:500,height:400});});
test('transparent PNG uses an alpha-preserving format and never increases file bytes',async()=>{const f=fixture(),source=f.file('image/png');assert.equal((await f.api.prepareImage(source)).type,'image/webp');assert.equal(f.getType(),'image/webp');const g=fixture();g.setOutputSize(3000000);const source2=g.file('image/png');assert.equal(await g.api.prepareImage(source2),source2);});
test('audio PDF vector and animation files are not recompressed',async()=>{const f=fixture();for(const type of ['audio/webm','application/pdf','image/svg+xml','image/gif']){const source=f.file(type);assert.equal(await f.api.prepareImage(source),source);}assert.equal(f.cleanup.length,0);});
test('decode failures clean up and remain retryable without an upload',async()=>{const f=fixture(),source=f.file();f.setDecodeFail(true);await assert.rejects(f.upload(source));assert.equal(f.getCalls(),0);assert.equal(f.cleanup.length,1);f.setDecodeFail(false);assert.equal((await f.upload(source)).ok,true);assert.equal(f.getCalls(),1);});
test('concurrent and repeated upload attempts reuse success with independently readable responses',async()=>{const f=fixture(),source=f.file();const [a,b]=await Promise.all([f.upload(source),f.upload(source)]);assert.equal((await a.json()).public_id,'test');assert.equal((await b.json()).public_id,'test');assert.equal((await (await f.upload(source)).json()).public_id,'test');assert.equal(f.getCalls(),1);assert.ok(f.bodies[0].get('file').size<source.size);});
test('failed provider requests are not reused; preset and expiry isolate future requests',async()=>{const f=fixture(),source=f.file();f.setFail(true);assert.equal((await f.upload(source)).ok,false);f.setFail(false);assert.equal((await f.upload(source)).ok,true);assert.equal(f.getCalls(),2);await f.upload(source,'another');assert.equal(f.getCalls(),3);f.expire();await f.upload(source);assert.equal(f.getCalls(),4);});
test('unsupported destination and oversized raster files never reach the provider',async()=>{const f=fixture(),body=new FormData();body.append('file',f.file());await assert.rejects(f.api.uploadCloudinary('https://example.com/upload',{method:'POST',body}));await assert.rejects(f.api.prepareImage(f.file('image/jpeg',31*1048576)));assert.equal(f.getCalls(),0);});
test('image delivery uses a small stable width set while video widths remain unchanged',()=>{const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/lib/cloudinaryDelivery.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{module,exports:module.exports,URL});const base='https://res.cloudinary.com/ffv5igmg/image/upload/v123/test.jpg';assert.equal(module.exports.cloudinaryImageUrl(base,850),module.exports.cloudinaryImageUrl(base,900));assert.match(module.exports.cloudinaryImageUrl(base,420),/w_420/);assert.match(module.exports.cloudinaryVideoUrl(base.replace('/image/','/video/'),720),/w_720/);assert.equal(module.exports.cloudinaryImageUrl('/api/media/video?id=1',900),'/api/media/video?id=1');});
