const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const url='https://res.cloudinary.com/ffv5igmg/image/upload/v123/notebooks/abc.jpg';
function fixture(){
 let config=true,extra=[],version=1,failDestroy=false,deleted=false,assetCalls=0,auditCalls=0,now=Date.now();const events=[];
 const ref={path:'notebookGallery/one',listCollections:async()=>[],get:async()=>({exists:!deleted,data:()=>({imageUrl:url}),updateTime:{toMillis:()=>version}}),delete:async({lastUpdateTime})=>{assert.equal(lastUpdateTime.toMillis(),version);events.push('record-delete');deleted=true;}};
 const row={ref,data:()=>({imageUrl:url})};
 const adminDb={collectionGroup:n=>({limit:()=>({get:async()=>({docs:[],size:0})})}),collection:n=>({doc:id=>{assert.equal(n,'notebookGallery');assert.equal(id,'one');return ref;}}),listCollections:async()=>{auditCalls++;return [{limit:n=>({get:async()=>{const docs=[row,...extra].slice(0,n);return {docs,size:docs.length};}})}];}};
 const mocks={'node:crypto':require('node:crypto'),'next/server':{NextResponse:{json:(body,options)=>({body,options})}},'next/cache':{revalidateTag:(tag,p)=>{assert.equal(tag,'public-gallery');assert.equal(p.expire,0);events.push('invalidate');}},'../../../../firebase-admin':{getFirebaseAdmin:()=>({adminDb,adminAuth:{verifyIdToken:async token=>{if(token==='bad')throw Error();return {uid:token,role:token==='student'?'student':'teacher'};}}})}};
 const env={};const fakeProcess={get env(){return config?{CLOUDINARY_CLOUD_NAME:'ffv5igmg',CLOUDINARY_API_KEY:'test-key',CLOUDINARY_API_SECRET:'test-secret'}:env;}};
 const module={exports:{}};
 const fakeDate=class extends Date{static now(){return now;}};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/teacher/notebook-delete/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>mocks[n],URL,URLSearchParams,Buffer,AbortSignal,Date:fakeDate,process:fakeProcess,fetch:async(u,opts)=>{assetCalls++;assert.ok(u.startsWith('https://api.cloudinary.com/v1_1/ffv5igmg/'));if(opts.method==='POST'){events.push('asset-delete');assert.equal(opts.body.get('asset_id'),'asset-123');assert.equal(opts.body.get('invalidate'),'true');return {ok:!failDestroy,json:async()=>({result:failDestroy?'error':'ok'})};}return {ok:true,json:async()=>({secure_url:url,public_id:'notebooks/abc',asset_id:'asset-123',bytes:1024})};}});
 const req=(action,token,who='teacher')=>({headers:{get:()=>who?'Bearer '+who:null},json:async()=>({id:'one',action,token})});
 return {api:module.exports,req,events,counts:()=>({assetCalls,auditCalls}),setConfig:v=>config=v,setExtra:values=>extra=values.map((data,i)=>({ref:{path:'others/'+i,listCollections:async()=>[]},data:()=>data})),change:()=>version++,fail:()=>failDestroy=true,advance:()=>now+=301000};
}
test('preview shows original bytes without deleting; delete orders asset before record',async()=>{const f=fixture(),p=await f.api.POST(f.req('preview'));assert.equal(p.body.bytes,1024);assert.equal(p.body.count,1);assert.equal(f.events.length,0);const d=await f.api.POST(f.req('delete',p.body.token));assert.equal(d.body.success,true);assert.deepEqual(f.events,['asset-delete','record-delete','invalidate']);assert.equal(f.counts().auditCalls,2);});
test('missing credentials fail before database audit or provider calls',async()=>{const f=fixture();f.setConfig(false);const r=await f.api.POST(f.req('preview'));assert.match(r.body.message,/مفاتيح/);assert.deepEqual(f.counts(),{assetCalls:0,auditCalls:0});});
test('unauthorized students cannot preview or delete',async()=>{const f=fixture();for(const who of [null,'bad','student'])assert.equal((await f.api.POST(f.req('preview',null,who))).body.success,false);assert.equal(f.counts().assetCalls,0);});
test('shared transformed image and nested public ID both block deletion',async()=>{for(const data of [{media:{url:'https://res.cloudinary.com/ffv5igmg/image/upload/w_200/v123/notebooks/abc.jpg'}},{media:{cloudinaryPublicId:'notebooks/abc'}}]){const f=fixture();f.setExtra([data]);assert.equal((await f.api.POST(f.req('preview'))).body.success,false);assert.equal(f.events.length,0);}});
test('references added after preview block execution',async()=>{const f=fixture(),p=await f.api.POST(f.req('preview'));f.setExtra([{imageUrl:url}]);assert.equal((await f.api.POST(f.req('delete',p.body.token))).body.success,false);assert.equal(f.events.length,0);});
test('provider failure preserves the Firestore record',async()=>{const f=fixture(),p=await f.api.POST(f.req('preview'));f.fail();assert.equal((await f.api.POST(f.req('delete',p.body.token))).body.success,false);assert.deepEqual(f.events,['asset-delete']);});
test('tampered, expired, other teacher, and stale previews cannot delete',async()=>{for(const variant of ['tampered','expired','teacher2','changed']){const f=fixture(),p=await f.api.POST(f.req('preview'));let token=p.body.token;if(variant==='tampered')token+='x';if(variant==='expired')f.advance();if(variant==='changed')f.change();assert.equal((await f.api.POST(f.req('delete',token,variant==='teacher2'?'teacher2':'teacher'))).body.success,false);assert.equal(f.events.length,0);}});
test('partial audit cannot authorize deletion past 500 records',async()=>{const f=fixture();f.setExtra(Array.from({length:501},()=>({fileUrl:'https://example.com/other.jpg'})));const r=await f.api.POST(f.req('preview'));assert.equal(r.body.success,false);assert.match(r.body.message,/500/);assert.equal(f.events.length,0);});
