const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function fixture(){
 const cache=new Map(),calls=[],tags=[];let fail=false;
 const rows=[{id:'a1',studentId:'a',title:'A',read:false,opened:false},{id:'b1',studentId:'b',title:'B',read:false}];
 const adminDb={collection(name){let student,cap,order;const q={where(f,op,v){assert.equal(f,'studentId');assert.equal(op,'==');student=v;return q;},orderBy(f,d){order=[f,d];return q;},limit(n){cap=n;return q;},async get(){calls.push({name,student,cap,order});if(fail)throw Error('quota');return {docs:rows.filter(r=>r.studentId===student).slice(0,cap).map(r=>({id:r.id,data:()=>({...r})}))};},doc(id){return {id};}};return q;},async runTransaction(fn){await fn({get:async ref=>{const r=rows.find(r=>r.id===ref.id);return {exists:!!r,data:()=>r};},update:(ref,patch)=>Object.assign(rows.find(r=>r.id===ref.id),patch)});}};
 const mocks={'node:crypto':require('node:crypto'),'next/server':{NextResponse:{json:(body,options)=>({body,options})}},'next/cache':{unstable_cache:(fn,keys,opts)=>async()=>{assert.equal(opts.revalidate,60);const key=JSON.stringify(keys);if(!cache.has(key))cache.set(key,{value:await fn(),tags:opts.tags});return cache.get(key).value;},revalidateTag:(tag,p)=>{assert.equal(p.expire,0);tags.push(tag);for(const [k,v]of cache)if(v.tags.includes(tag))cache.delete(k);}},'firebase-admin/firestore':{FieldValue:{serverTimestamp:()=>123}},'../../../firebase-admin':{getFirebaseAdmin:()=>({adminDb,adminAuth:{verifyIdToken:async t=>{if(t==='invalid')throw Error('bad token');return {role:t==='teacher'?'teacher':'student',studentDocId:t};}}})}};
 const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/student-notifications/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>mocks[n],console:{error(){}}});
 return {api:module.exports,calls,tags,setFail:v=>fail=v,req:(token,body)=>({headers:{get:()=>token?'Bearer '+token:null},json:async()=>body})};
}
test('repeat loads reuse a bounded student-specific cache and keep responses private',async()=>{const f=fixture();for(let i=0;i<5;i++){const r=await f.api.GET(f.req('a'));assert.equal(r.body.notifications[0].id,'a1');assert.equal(r.options.headers['Cache-Control'],'private, no-store');}assert.equal(f.calls.length,1);assert.equal(f.calls[0].cap,12);assert.deepEqual(f.calls[0].order,['createdAt','desc']);assert.equal((await f.api.GET(f.req('b'))).body.notifications[0].id,'b1');assert.equal(f.calls.length,2);});
test('authentication is checked on cache hits and unauthorized requests never query',async()=>{const f=fixture();await f.api.GET(f.req('a'));for(const token of [null,'invalid','teacher']){assert.equal((await f.api.GET(f.req(token))).body.success,false);}assert.equal(f.calls.length,1);});
test('opening a gift invalidates only its owners cache after a successful write',async()=>{const f=fixture();await f.api.GET(f.req('a'));await f.api.GET(f.req('b'));assert.equal((await f.api.POST(f.req('a',{notificationId:'a1',opened:true}))).body.success,true);const r=await f.api.GET(f.req('a'));assert.equal(r.body.notifications[0].read,true);assert.equal(r.body.notifications[0].opened,true);await f.api.GET(f.req('b'));assert.equal(f.calls.length,3);assert.equal(f.tags.length,1);});
test('attempt to change another students notification cannot invalidate the cache',async()=>{const f=fixture();await f.api.GET(f.req('a'));assert.equal((await f.api.POST(f.req('b',{notificationId:'a1'}))).body.success,false);assert.equal(f.tags.length,0);assert.equal((await f.api.GET(f.req('a'))).body.notifications[0].read,false);assert.equal(f.calls.length,1);});
test('failed database loads are not cached as empty successful results',async()=>{const f=fixture();f.setFail(true);assert.equal((await f.api.GET(f.req('a'))).body.success,false);f.setFail(false);assert.equal((await f.api.GET(f.req('a'))).body.notifications.length,1);assert.equal(f.calls.length,2);});
