const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,mocks){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>{if(!(n in mocks))throw Error(n);return mocks[n]},URL,URLSearchParams,console});return module.exports;}
class Timestamp{constructor(seconds,nanoseconds=0){this.seconds=seconds;this.nanoseconds=nanoseconds;}toMillis(){return this.seconds*1000+this.nanoseconds/1e6;}toDate(){return new Date(this.toMillis());}}
function fixture(){
 const calls=[],cache=new Map(),tags=[],rows={};
 rows.studentWorks=Array.from({length:67},(_,i)=>({id:'w'+String(i).padStart(3,'0'),studentId:'s',status:i%3===0?'pending':i%2?'approved':'معتمد',published:i%3!==0,fileUrl:'image-'+i,createdAt:new Timestamp(100,100000-i)}));
 rows.notebookGallery=Array.from({length:45},(_,i)=>({id:'n'+i,studentId:'s',imageUrl:'notebook-'+i,isPublished:i%4!==0,publishedAt:new Timestamp(99,200000-i)}));
 rows.classDiary=Array.from({length:47},(_,i)=>({id:'d'+String(i).padStart(3,'0'),isPublished:i!==0,title:'day'+i,createdAt:new Timestamp(200-i)}));
 rows.weeklyPlans=[{id:'current',published:true,weekTitle:'week',days:[],privateField:'never public'}];
 rows.academyHeroes=[{id:'h',published:false,studentFirstName:'private'},{id:'p',published:true,studentFirstName:'public',privateField:'secret'}];rows.galleryHighlights=[];
 const doc=x=>({id:x.id,exists:true,data:()=>x,get:f=>x[f]});
 const adminDb={collection(name){let filters=[],orders=[],cursor,cap=Infinity;const q={where(f,op,v){filters.push([f,op,v]);return q;},orderBy(f,d){orders.push([f,d]);return q;},startAfter(...v){cursor=v;return q;},limit(n){cap=n;return q;},doc(id){return {id,async get(){calls.push({name,doc:id});const x=(rows[name]||[]).find(x=>x.id===id);return x?doc(x):{exists:false,data:()=>undefined};}}},async get(){calls.push({name,cap});let xs=(rows[name]||[]).filter(x=>filters.every(([f,op,v])=>x[f]===v));if(orders[0]?.[0]!=='__name__'){const f=orders[0]?.[0];xs=xs.filter(x=>x[f]);xs.sort((a,b)=>b[f].toMillis()-a[f].toMillis()||b.id.localeCompare(a.id));if(cursor){const time=cursor[0].data?cursor[0].get(f):cursor[0],id=cursor[0].data?cursor[0].id:cursor[1];xs=xs.filter(x=>x[f].toMillis()<time.toMillis()||(x[f].toMillis()===time.toMillis()&&x.id<id));}}else xs.sort((a,b)=>a.id.localeCompare(b.id));xs=xs.slice(0,cap);return {docs:xs.map(doc),size:xs.length,empty:!xs.length};}};return q;},async getAll(...refs){calls.push({name:'students',cap:refs.length});return refs.map(r=>doc({id:r.id,personalPhotoStatus:'approved',personalPhotoUrl:'portrait'}));}};
 const mocks={'next/cache':{unstable_cache:(fn,key,opt)=>async(...args)=>{const k=JSON.stringify([key,args]);if(!cache.has(k))cache.set(k,await fn(...args));return cache.get(k);},revalidateTag:(tag,profile)=>{assert.equal(profile.expire,0);tags.push(tag);cache.clear();}},'next/server':{NextResponse:{json:(body,options)=>({body,options})}},'firebase-admin/firestore':{Timestamp,FieldPath:{documentId:()=> '__name__'}},'../../../firebase-admin':{getFirebaseAdmin:()=>({adminDb})},'../../../../firebase-admin':{getFirebaseAdmin:()=>({adminAuth:{verifyIdToken:async token=>token==='teacher'?{role:'teacher'}:{role:'student'}}})}};
 return {calls,tags,rows,content:load('app/api/public-content/route.ts',mocks),gallery:load('app/api/gallery/route.ts',mocks),invalidate:load('app/api/teacher/public-content-cache/route.ts',mocks)};
}
const req=(url,token)=>({url:'https://test/'+url,headers:{get:()=>token?'Bearer '+token:null}});
test('shared plan cache reuses queries and strips non-public fields; teacher invalidation refreshes publication',async()=>{const f=fixture();for(let i=0;i<4;i++){const r=await f.content.GET(req('?kind=plan'));assert.equal(r.body.documents[0].data.privateField,undefined);}assert.equal(f.calls.length,1);assert.equal((await f.invalidate.POST(req('', 'student'))).options.status,403);assert.equal(f.tags.length,0);await f.invalidate.POST(req('', 'teacher'));await f.content.GET(req('?kind=plan'));assert.equal(f.calls.length,2);assert.ok(f.tags.includes('shared-public-content'));});
test('diary archive pages are bounded and contain all published records once',async()=>{const f=fixture(),seen=[];let cursor='';do{const r=await f.content.GET(req('?'+new URLSearchParams({kind:'diary',cursor})));assert.equal(r.body.success,true);seen.push(...r.body.documents.map(x=>x.id));cursor=r.body.nextCursor;}while(cursor);assert.equal(new Set(seen).size,46);assert.equal(seen.length,46);assert.ok(f.calls.filter(x=>!x.doc).every(x=>x.cap===20));const latest=await f.content.GET(req('?kind=latestDiary'));assert.equal(latest.body.documents[0].id,'d001');});
test('gallery scans at most thirty documents per source and preserves nanosecond cursor ordering',async()=>{const f=fixture(),works=[],notebooks=[];let cursors={works:'',notebooks:''};do{const url='?'+new URLSearchParams({worksCursor:cursors.works,notebooksCursor:cursors.notebooks});const r=await f.gallery.GET(req(url));assert.equal(r.body.success,true);works.push(...r.body.works.map(x=>x.id));notebooks.push(...r.body.notebooks.map(x=>x.id));cursors=r.body.cursors;}while(cursors.works!=='done'||cursors.notebooks!=='done');assert.equal(works.length,44);assert.equal(new Set(works).size,44);assert.equal(notebooks.length,33);assert.equal(new Set(notebooks).size,33);assert.ok(f.calls.filter(x=>x.name!=='students').every(x=>x.cap===30));const before=f.calls.length;await f.gallery.GET(req('?worksCursor=done&notebooksCursor=done'));assert.equal(f.calls.length,before);});
test('malformed gallery cursors fail before Firestore access',async()=>{const f=fixture();assert.equal((await f.gallery.GET(req('?worksCursor=broken'))).options.status,400);assert.equal(f.calls.length,0);});
test('hidden scoreboards unsubscribe and restore exactly one listener on return',()=>{let hidden=false,handler,started=0,stopped=0;const visibility={get hidden(){return hidden},addEventListener:(_,h)=>handler=h,removeEventListener:()=>handler=undefined};const api=load('app/lib/visibleSubscription.ts',{});const stop=api.startVisibleSubscription(()=>{started++;return ()=>stopped++},visibility);assert.equal(started,1);hidden=true;handler();handler();assert.equal(stopped,1);hidden=false;handler();handler();assert.equal(started,2);stop();assert.equal(stopped,2);assert.equal(handler,undefined);});
test('anonymous weekly preview cannot trigger weekly activity scans',async()=>{let reads=0;const api=load('app/api/public-weekly-engagement/route.ts',{'next/cache':{unstable_cache:fn=>fn},'next/server':{NextResponse:{json:(body,options)=>({body,options})}},'firebase-admin/firestore':{FieldValue:{}},'../../../firebase-admin':{getFirebaseAdmin:()=>{reads++;throw Error('unexpected access')}}});const r=await api.GET(req('api/public-weekly-engagement?teacherPreview=1'));assert.equal(r.options.status,401);assert.equal(reads,0);});
