const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function fixture(){let configured=true,providerCalls=0,r2Calls=0,dbCalls=0,authCalls=0,fail=false;const cache=new Map(),queries=[],now=Date.now();const rows=[{id:'old',data:{studentName:'طالب',createdAt:{toMillis:()=>now-40*86400000}}},{id:'recent',data:{createdAt:{toMillis:()=>now-3*86400000}}},{id:'published',data:{createdAt:{toMillis:()=>now-40*86400000},publishedToGallery:true}},{id:'recently-rejected',data:{createdAt:{toMillis:()=>now-40*86400000},rejectedAt:{toMillis:()=>now-2*86400000}}}];
 const adminDb={collection:name=>{const q={where:(field,op,value)=>{queries.push({name,field,op,value});return q;},limit:n=>{assert.equal(n,25);return q;},get:async()=>{dbCalls++;return {size:rows.length,docs:rows.map(r=>({id:r.id,data:()=>r.data}))};}};return q;}};
 const mocks={'next/server':{NextResponse:{json:(body,options)=>({body,options})}},'next/cache':{unstable_cache:(fn,key,opts)=>async()=>{assert.equal(opts.revalidate,300);const k=JSON.stringify(key);if(!cache.has(k))cache.set(k,await fn());return cache.get(k);}},'../../../../firebase-admin':{getFirebaseAdmin:()=>({adminDb,adminAuth:{verifyIdToken:async t=>{authCalls++;if(t==='bad')throw Error();return {role:t,uid:t};}}})},'../../../lib/r2Video':{listVideoStorage:async cursor=>{r2Calls++;return {items:[{id:'media/a',bytes:10}],nextCursor:cursor?'':'next'};}}};
 const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/teacher/storage-review/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>mocks[n],Buffer,AbortSignal,process:{get env(){return configured?{CLOUDINARY_CLOUD_NAME:'ffv5igmg',CLOUDINARY_API_KEY:'mock',CLOUDINARY_API_SECRET:'mock'}:{};}},fetch:async(u,opts)=>{providerCalls++;assert.equal(u,'https://api.cloudinary.com/v1_1/ffv5igmg/resources/search');assert.equal(opts.method,'POST');const b=JSON.parse(opts.body);assert.equal(b.max_results,50);assert.deepEqual(b.sort_by,[{bytes:'desc'}]);if(fail)return {ok:false};return {ok:true,json:async()=>({resources:[{asset_id:'a',public_id:'first',resource_type:'image',bytes:20,etag:'same',secure_url:'secret-url'},{asset_id:'b',public_id:'second',resource_type:'image',bytes:20,etag:'same'}],next_cursor:'next'})};}});
 return {api:module.exports,req:(source='cloudinary',who='teacher',cursor='')=>({headers:{get:()=>who?'Bearer '+who:null},json:async()=>({source,cursor})}),counts:()=>({providerCalls,r2Calls,dbCalls,authCalls}),disable:()=>configured=false,fail:v=>fail=v,queries};}
test('all inventory sources require teacher authentication before any reads',async()=>{const f=fixture();for(const source of ['cloudinary','r2','retention'])for(const who of [null,'student','bad'])assert.equal((await f.api.POST(f.req(source,who))).body.success,false);assert.equal(f.counts().providerCalls+f.counts().dbCalls+f.counts().r2Calls,0);});
test('absent Cloudinary secrets stop inventory without scanning Firestore',async()=>{const f=fixture();f.disable();const r=await f.api.POST(f.req());assert.equal(r.options.status,409);assert.equal(f.counts().providerCalls+f.counts().dbCalls,0);});
test('cloud metadata is bounded, cached, and contains no media URLs or provider credentials',async()=>{const f=fixture();for(let i=0;i<3;i++){const r=await f.api.POST(f.req());assert.equal(r.body.items.length,2);assert.equal(r.body.items[0].duplicate,true);assert.equal(r.options.headers['Cache-Control'],'private, no-store');assert.equal(r.body.nextCursor,'next');assert.equal(JSON.stringify(r.body).includes('secret-url'),false);}assert.equal(f.counts().providerCalls,1);assert.equal(f.counts().authCalls,3);assert.equal((await f.api.POST(f.req('cloudinary','student'))).options.status,403);assert.equal(f.counts().providerCalls,1);});
test('provider failures are not cached as successful empty inventories',async()=>{const f=fixture();f.fail(true);assert.equal((await f.api.POST(f.req())).body.success,false);f.fail(false);assert.equal((await f.api.POST(f.req())).body.success,true);assert.equal(f.counts().providerCalls,2);});
test('R2 pages are distinct and reuse cached metadata without media downloads',async()=>{const f=fixture();await f.api.POST(f.req('r2'));await f.api.POST(f.req('r2'));await f.api.POST(f.req('r2','teacher','next'));assert.equal(f.counts().r2Calls,2);assert.equal(f.counts().providerCalls+f.counts().dbCalls,0);});
test('retention review excludes recent and published work and uses rejection time when available',async()=>{const f=fixture(),r=await f.api.POST(f.req('retention'));assert.equal(r.body.items.length,3);assert.ok(r.body.items.every(i=>i.id.endsWith('/old')));assert.equal(r.body.checkedRecords,12);assert.equal(f.counts().dbCalls,3);assert.ok(f.queries.every(q=>q.field==='status'&&q.op==='=='));await f.api.POST(f.req('retention'));assert.equal(f.counts().dbCalls,3);});
test('unknown sources and oversized cursors are rejected without provider calls',async()=>{const f=fixture();for(const req of [f.req('delete'),f.req('r2','teacher','x'.repeat(2049))])assert.equal((await f.api.POST(req)).options.status,400);assert.equal(f.counts().r2Calls+f.counts().providerCalls+f.counts().dbCalls,0);});
test('R2 listing sends one 50-object prefix-limited request and sorts only its current page',async()=>{const calls=[],module={exports:{}};class ListObjectsV2Command{constructor(input){this.input=input;}}class S3Client{async send(cmd){calls.push(cmd);return {IsTruncated:true,NextContinuationToken:'next',Contents:[{Key:'media/a',Size:1},{Key:'media/b',Size:10}]};}}
 const mocks={'server-only':{},'@aws-sdk/client-s3':{S3Client,ListObjectsV2Command},'@aws-sdk/s3-request-presigner':{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/lib/r2Video.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{module,exports:module.exports,require:n=>mocks[n],process:{env:{R2_ACCOUNT_ID:'mock',R2_BUCKET_NAME:'lughati-videos',R2_ACCESS_KEY_ID:'mock',R2_SECRET_ACCESS_KEY:'mock'}}});const r=await module.exports.listVideoStorage('cursor');assert.equal(calls.length,1);assert.equal(calls[0].input.MaxKeys,50);assert.equal(calls[0].input.Prefix,'media/');assert.equal(calls[0].input.ContinuationToken,'cursor');assert.equal(r.items[0].id,'media/b');assert.equal(r.nextCursor,'next');});
