"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {onAuthStateChanged,type User} from "firebase/auth";import {auth} from "../../../../firebase";
export default function TeacherCouncil(){const [user,setUser]=useState<User|null>(null),[q,setQ]=useState(""),[opts,setOpts]=useState(["",""]),[hours,setHours]=useState("24"),[show,setShow]=useState(false),[poll,setPoll]=useState<any>(null),[msg,setMsg]=useState("");
useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);if(u)void load(u)}),[]);
async function load(u:User){const t=await u.getIdToken();const r=await fetch("/api/teacher/academy-club/council",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const d=await r.json();if(r.ok)setPoll(d.poll)}
async function publish(){if(!user)return;const t=await user.getIdToken();const r=await fetch("/api/teacher/academy-club/council",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({question:q,options:opts,durationHours:Number(hours),showResults:show})});const d=await r.json();setMsg(r.ok?"تم نشر التصويت لأعضاء النادي 🗳️":d.message);if(r.ok){setQ("");setOpts(["",""]);await load(user)}}
async function patch(x:any){if(!user)return;const t=await user.getIdToken();await fetch("/api/teacher/academy-club/council",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify(x)});await load(user)}
const input={padding:12,borderRadius:12,border:"1px solid #bdd6c9",font:"inherit",width:"100%",boxSizing:"border-box" as const};
return <main dir="rtl" style={{minHeight:"100vh",background:"#f4faf7",fontFamily:"Arial",color:"#17352a"}}><header style={{background:"linear-gradient(135deg,#176c46,#0f5237)",color:"white",padding:"25px max(16px,calc((100% - 950px)/2))",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><b style={{color:"#f4d46a"}}>🏅 نادي الأكاديمية</b><h1>🗳️ إدارة مجلس النادي</h1></div><Link href="/teacher/academy-club" style={{color:"white"}}>العودة ←</Link></header><div style={{maxWidth:950,margin:"0 auto",padding:20,display:"grid",gap:18}}><section style={{background:"white",borderRadius:22,padding:23,border:"1px solid #d7e8df"}}><h2>إنشاء تصويت جديد</h2><label style={{display:"grid",gap:7,fontWeight:900}}>سؤال التصويت<textarea rows={3} value={q} onChange={e=>setQ(e.target.value)} style={input}/></label><h3>الخيارات</h3>{opts.map((o,i)=><div key={i} style={{display:"flex",gap:8,marginBottom:9}}><input value={o} onChange={e=>setOpts(a=>a.map((v,j)=>j===i?e.target.value:v))} placeholder={`الخيار ${i+1}`} style={input}/>{opts.length>2&&<button onClick={()=>setOpts(a=>a.filter((_,j)=>j!==i))}>حذف</button>}</div>)}{opts.length<4&&<button onClick={()=>setOpts(a=>[...a,""])}>＋ إضافة خيار</button>}<div style={{display:"flex",gap:15,flexWrap:"wrap",marginTop:17}}><label>مدة التصويت <select value={hours} onChange={e=>setHours(e.target.value)}><option value="6">6 ساعات</option><option value="12">12 ساعة</option><option value="24">يوم</option><option value="48">يومان</option><option value="72">3 أيام</option></select></label><label><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> إظهار النتائج للطلاب</label></div><button onClick={()=>void publish()} style={{marginTop:18,padding:"13px 22px",border:0,borderRadius:14,background:"#176c46",color:"white",fontWeight:900}}>🚀 نشر التصويت</button>{msg&&<p style={{fontWeight:900}}>{msg}</p>}</section>{poll&&<section style={{background:"white",borderRadius:22,padding:23,border:"1px solid #d7e8df"}}><h2>التصويت الحالي</h2><h3 style={{color:"#176c46"}}>{poll.question}</h3>{poll.options.map((o:string,i:number)=><div key={i} style={{padding:10,borderBottom:"1px solid #eee"}}>{o} — <b>{poll.counts?.[String(i)]??0}</b></div>)}<p><b>إجمالي المشاركين: {poll.totalVotes??0}</b></p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={()=>void patch({showResults:!poll.showResults})}>{poll.showResults?"🙈 إخفاء النتائج":"👁️ إظهار النتائج"}</button><button onClick={()=>void patch({active:!poll.active})}>{poll.active?"🔒 إغلاق التصويت":"🔓 إعادة فتح التصويت"}</button><Link href="/academy-club/council" target="_blank">معاينة الغرفة</Link></div></section>}</div></main>}
